services:
  frontend:
    build:
      target: base
    command: npm start -- --host 0.0.0.0
    #command: sleep infinity
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    volumes:
      - .:/usr/src/app # Volume para hot-reload do c√≥digo
      - /usr/src/app/node_modules # Isola o node_modules
    environment:
      - NODE_ENV=development # Define o ambiente como desenvolvimento
