services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-angular-portal-ong-ser-amor
    # Vari√°veis de ambiente para build do Angular
    environment:
      - API_URL=${API_URL:-http://localhost:3000}
